# Check `ares-sc2/src/ares/config.yml` for valid config options
# Use this to override those values
# Can add own unique config options here if desired

# Set custom values here for your bot
MyBotName: MyBotName
MyBotRace: Random
# setting ture allows auto upload to aiareana (https://aiarena.net/) on push to `main` branch
# see tutorial on readme before setting to True
AutoUploadToAiarena: False
########################

UseData: False
Debug: False
GameStep: 2
DebugGameStep: 2

DebugOptions:
    # one of: Air, AirVsGround, Ground, GroundAvoidance, AirAvoidance
    ActiveGrid: Ground
    ChatDebug: True
    DebugSpawn: False
    ShowPathingCost: False
    ResourceDebug: False
