# Check `ares-sc2/src/ares/config.yml` for valid config options
# Use this to override those values
# Can add own unique config options here if desired

# Custom values not used by ares
MyBotName: MyBotName
MyBotRace: Random
########################

UseData: False
Debug: False
GameStep: 2
DebugGameStep: 2

DebugOptions:
    # one of: Air, AirVsGround, Ground, GroundAvoidance, AirAvoidance
    ActiveGrid: Ground
    ChatDebug: True
    DebugSpawn: False
    ShowPathingCost: False
    ResourceDebug: False
