name: Build Windows Executable

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for building'
        required: false
        default: 'Manual build'
        type: string


jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: Install dependencies
      run: |
        poetry install --no-interaction
        poetry run pip install pyinstaller

    - name: Debug Info
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        dir
        echo "Python path:"
        poetry run python -c "import sys; print(sys.executable)"

    - name: Build executable
      run: |
        poetry run python scripts/create_pyinstaller_exe.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: |
          publish/*.exe
          publish/ladderbots.json
          publish/*.yml
          publish/*.yaml