name: Build Windows Executable

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create false

    - name: Install dependencies
      run: |
        poetry install --no-interaction --with dev
        python -m pip install pyinstaller

    - name: Debug Info
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        dir
        echo "Python path:"
        python -c "import sys; print(sys.executable)"
        echo "PyInstaller path:"
        where pyinstaller

    - name: Build executable
      shell: cmd
      run: |
        poetry run pyinstaller --name ares ^
          --add-data "ares;ares" ^
          --add-data "config;config" ^
          --add-data "requirements.txt;." ^
          --add-data "poetry.lock;." ^
          --add-data "pyproject.toml;." ^
          run.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: |
          dist/*.exe
          dist/ares/*
